In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [3]:
c = np.array([2,3,4,5,6,2]).reshape(2,3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [5]:
e = np.array([1,2,3,4,5,6])
print(e.max())
print(e.sum())
print(e.min())
print(e.mean())

6
21
1
3.5


In [10]:
np.zeros(5) # Create array of zeros with five elements
np.linspace(0,6,10) # Creates array of value from 0 through 6 in 10 even spaces
np.random.rand(3) # Thre "random" values between 0 and 1
np.random.randint(1,100) # "Random" ingeteger between 1 and 100
np.arange(25) # Gives you a Range of integers between 1-25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [13]:
np.random.rand(3) # Thre "random" values between 0 and 1

array([0.37998997, 0.15272627, 0.93448501])

In [14]:
np.random.randint(1,100) # "Random" ingeteger between 1 and 100

87

In [15]:
np.arange(25) # Gives you a Range of integers between 1-25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])